<template lang="">
    <div class="container">
		<h1 class="title-page d-none">
			<span>Bắt kịp xu hướng</span>
		</h1>
		<div class="row">
			
			<div class="blog_left_base col-lg-3 col-12 order-2 order-lg-1">
				

            <div class="aside-content aside-content-blog">
                <div class="title-head">
                    Danh mục tin tức
                </div>
                <nav class="nav-category">
                    <ul class="nav navbar-pills">
                        <li class="nav-item active relative">
                            <a title="Bắt kịp xu hướng" class="nav-link" href="/bat-kip-xu-huong">Bắt kịp xu hướng</a>
                        </li>
                        <li class="nav-item  relative">
                            <a title="Xây dựng phong cách" class="nav-link" href="/xay-dung-phong-cach">Xây dựng phong cách</a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="blog_noibat">
                <h2 class="h2_sidebar_blog">
                    <a href="/tin-tuc" title="Tin tức nổi bật">Tin tức nổi bật</a>
                </h2>
                <div class="blog_content">
                    
                    <div class="item clearfix">
                        <div class="post-thumb">
                            <a class="image-blog scale_hover" href="/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit-2" title="Lorem ipsum dolor sit amet, consectetur adipiscing elit">
                                
                                <img class="img_blog lazyload loaded" src="https://bizweb.dktcdn.net/100/491/897/articles/rectangle-70.png?v=1691052763477" data-src="https://bizweb.dktcdn.net/100/491/897/articles/rectangle-70.png?v=1691052763477" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit" data-was-processed="true">
                                
                            </a>
                        </div>
                        <div class="contentright">
                            <h3><a title="Lorem ipsum dolor sit amet, consectetur adipiscing elit" href="/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a></h3>

                        </div>
                    </div>
                    
                    <div class="item clearfix">
                        <div class="post-thumb">
                            <a class="image-blog scale_hover" href="/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit-1" title="Lorem ipsum dolor sit amet, consectetur adipiscing elit">
                                
                                <img class="img_blog lazyload loaded" src="https://bizweb.dktcdn.net/100/491/897/articles/rectangle-71.png?v=1691052751867" data-src="https://bizweb.dktcdn.net/100/491/897/articles/rectangle-71.png?v=1691052751867" alt="Lorem ipsum dolor sit amet, consectetur adipiscing elit" data-was-processed="true">
                                
                            </a>
                        </div>
                        <div class="contentright">
                            <h3><a title="Lorem ipsum dolor sit amet, consectetur adipiscing elit" href="/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit-1">Lorem ipsum dolor sit amet, consectetur adipiscing elit</a></h3>

                        </div>
                    </div>
                    
                </div>
            </div>
			</div>
			<div class="right-content col-lg-9 col-12 order-1 order-lg-2">



				
				<div class="list-blogs">
					
					<div class="row row-fix">
							
						<div class="col-12 col-md-6 col-lg-6 col-xl-4 col-fix">
							<div class="item-blog">
                                <div class="block-thumb">
                                    
                                    <a class="thumb" href="/phoi-do-voi-quan-relax-chuan-men-danh-cho-nam" title="Phối đồ với quần relax chuẩn men dành cho nam">
                                        <img width="512" height="385" class="lazyload loaded" src="https://bizweb.dktcdn.net/100/491/897/articles/phoi-do-voi-form-relax-chuan-men.png?v=1693032957567" data-src="https://bizweb.dktcdn.net/100/491/897/articles/phoi-do-voi-form-relax-chuan-men.png?v=1693032957567" alt="Phối đồ với quần relax chuẩn men dành cho nam" data-was-processed="true">
                                    </a>
                                    
                                    <div class="info">


                                        <h3>
                                            <a class="line-clamp line-clamp-1" href="/phoi-do-voi-quan-relax-chuan-men-danh-cho-nam" title="Phối đồ với quần relax chuẩn men dành cho nam">Phối đồ với quần relax chuẩn men dành cho nam</a>
                                        </h3>
                                        <p class="justify line-clamp line-clamp-3">Tuy nhiên,&nbsp;form relax&nbsp;được biết đến là một form quần rộng rãi với phần ống rộng nên có rất nhiều chàng trai không biết phải phối đồ cùng form quần này như thế nào để không bị xuề xòa, luộm thuộm. Nhưng không cần lo lắng, vì trong bài viết ngày hôm nay Routine sẽ mách cho bạn&nbsp;cách mix quần nam ống rộng chuẩn men, sành điệu&nbsp;nhất cho các chàng, cùng theo dõi nhé
                            1. Quần form relax phối cùng áo sơ mi trắng basic
                            Nếu bạn đang đau đầu vì không biết&nbsp;phối đồ với quần form relax như thế nào, tại sao...</p>
                                        
                                        <a class="see" href="/phoi-do-voi-quan-relax-chuan-men-danh-cho-nam" title="Xem thêm">
                                            <span><svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32V224H48c-17.7 0-32 14.3-32 32s14.3 32 32 32H192V432c0 17.7 14.3 32 32 32s32-14.3 32-32V288H400c17.7 0 32-14.3 32-32s-14.3-32-32-32H256V80z"></path></svg></span> Xem thêm
                                        </a>
                                        
                                    </div>

                                    <div class="time-post">
                                        Ngày 26, Tháng 08, 2023
                                    </div>
                                </div>

                            </div>
						</div>

							
						<div class="col-12 col-md-6 col-lg-6 col-xl-4 col-fix">
							<div class="item-blog">
                                <div class="block-thumb">
                                    
                                    <a class="thumb" href="/goi-y-5-kieu-quan-kaki-nu-tre-trung-duoc-gioi-tre-lang-xe" title="Gợi ý 5 kiểu quần kaki nữ trẻ trung được giới trẻ lăng xê">
                                        <img width="512" height="385" class="lazyload loaded" src="https://bizweb.dktcdn.net/100/491/897/articles/quan-kaki-nu-thumb.png?v=1693032395680" data-src="https://bizweb.dktcdn.net/100/491/897/articles/quan-kaki-nu-thumb.png?v=1693032395680" alt="Gợi ý 5 kiểu quần kaki nữ trẻ trung được giới trẻ lăng xê" data-was-processed="true">
                                    </a>
                                    
                                    <div class="info">


                                        <h3>
                                            <a class="line-clamp line-clamp-1" href="/goi-y-5-kieu-quan-kaki-nu-tre-trung-duoc-gioi-tre-lang-xe" title="Gợi ý 5 kiểu quần kaki nữ trẻ trung được giới trẻ lăng xê">Gợi ý 5 kiểu quần kaki nữ trẻ trung được giới trẻ lăng xê</a>
                                        </h3>
                                        <p class="justify line-clamp line-clamp-3">Quần kaki nữ&nbsp;là một trong những item thoải mái, năng động 'must have' trong tủ đồ các nàng, phù hợp với cả cô nàng công sở đến phong cách thời trang hằng ngày. Quần kaki không chỉ sở hữu thiết kế, form dáng đa dạng mà ngày càng có nhiều lựa chọn hơn về màu sắc và chất vải. Với vô vàn lựa chọn, Denny sẽ gợi ý ngay đến bạn&nbsp;5 kiểu quần kaki nữ trẻ trung được giới trẻ yêu thích&nbsp;và lăng xê trong thời gian gần đây
                            1. Quần kaki nữ là gì?&nbsp;
                            Những dáng người phù hợp mặc quần...</p>
                                        
                                        <a class="see" href="/goi-y-5-kieu-quan-kaki-nu-tre-trung-duoc-gioi-tre-lang-xe" title="Xem thêm">
                                            <span><svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32V224H48c-17.7 0-32 14.3-32 32s14.3 32 32 32H192V432c0 17.7 14.3 32 32 32s32-14.3 32-32V288H400c17.7 0 32-14.3 32-32s-14.3-32-32-32H256V80z"></path></svg></span> Xem thêm
                                        </a>
                                        
                                    </div>

                                    <div class="time-post">
                                        Ngày 26, Tháng 08, 2023
                                    </div>
                                </div>

                            </div>
						</div>

							
						<div class="col-12 col-md-6 col-lg-6 col-xl-4 col-fix">
							<div class="item-blog">
                                <div class="block-thumb">
                                    
                                    <a class="thumb" href="/sportswear-la-gi-chat-lieu-lam-nen-nhung-bo-sportswear-cao-cap" title="Sportswear là gì? Chất liệu làm nên những bộ sportswear cao cấp">
                                        <img width="512" height="385" class="lazyload loaded" src="https://bizweb.dktcdn.net/100/491/897/articles/sportswear-la-gi-chat-lieu-lam-n.png?v=1693032295757" data-src="https://bizweb.dktcdn.net/100/491/897/articles/sportswear-la-gi-chat-lieu-lam-n.png?v=1693032295757" alt="Sportswear là gì? Chất liệu làm nên những bộ sportswear cao cấp" data-was-processed="true">
                                    </a>
                                    
                                    <div class="info">


                                        <h3>
                                            <a class="line-clamp line-clamp-1" href="/sportswear-la-gi-chat-lieu-lam-nen-nhung-bo-sportswear-cao-cap" title="Sportswear là gì? Chất liệu làm nên những bộ sportswear cao cấp">Sportswear là gì? Chất liệu làm nên những bộ sportswear cao cấp</a>
                                        </h3>
                                        <p class="justify line-clamp line-clamp-3">Nếu đã là một người đam mê thể thao, thích vận động chắc hẳn bạn sẽ không thể nào bỏ qua những trang phục thời trang phổ biến như&nbsp;sportswear.&nbsp;Sportswear&nbsp;luôn mang lại cho người mặc sự thoải mái, tự do vận động, thoáng mát trong suốt ngày dài. Đây cũng là một loại trang phục rất được yêu thích, sử dụng một cách phổ biến trong cuộc sống hàng ngày. Vậy&nbsp;Phong cách Sportswear là gì?&nbsp;Nó mang những đặc điểm gì mà lại nhận được nhiều sự ưa chuộng như vậy? Cùng khám phá ngay trong bài viết ngày hôm nay nhé!
                            1....</p>
                                        
                                        <a class="see" href="/sportswear-la-gi-chat-lieu-lam-nen-nhung-bo-sportswear-cao-cap" title="Xem thêm">
                                            <span><svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32V224H48c-17.7 0-32 14.3-32 32s14.3 32 32 32H192V432c0 17.7 14.3 32 32 32s32-14.3 32-32V288H400c17.7 0 32-14.3 32-32s-14.3-32-32-32H256V80z"></path></svg></span> Xem thêm
                                        </a>
                                        
                                    </div>

                                    <div class="time-post">
                                        Ngày 26, Tháng 08, 2023
                                    </div>
                                </div>

                            </div>
						</div>

							
						<div class="col-12 col-md-6 col-lg-6 col-xl-4 col-fix">
							<div class="item-blog">
                                <div class="block-thumb">
                                    
                                    <a class="thumb" href="/phong-cach-thoi-trang-duoc-gen-z-nhiet-tinh-lang-xe-2023" title="Phong cách thời trang được Gen Z nhiệt tình lăng xê 2023">
                                        <img width="512" height="385" class="lazyload loaded" src="https://bizweb.dktcdn.net/100/491/897/articles/phong-cach-gen-z-1.png?v=1693032818170" data-src="https://bizweb.dktcdn.net/100/491/897/articles/phong-cach-gen-z-1.png?v=1693032818170" alt="Phong cách thời trang được Gen Z nhiệt tình lăng xê 2023" data-was-processed="true">
                                    </a>
                                    
                                    <div class="info">


                                        <h3>
                                            <a class="line-clamp line-clamp-1" href="/phong-cach-thoi-trang-duoc-gen-z-nhiet-tinh-lang-xe-2023" title="Phong cách thời trang được Gen Z nhiệt tình lăng xê 2023">Phong cách thời trang được Gen Z nhiệt tình lăng xê 2023</a>
                                        </h3>
                                        <p class="justify line-clamp line-clamp-3">Phong cách thời trang 2023&nbsp;mang đặc trưng của sự phóng khoáng, năng động, độc đáo và mới lạ ngày càng lên ngôi và được thế hệ Gen Z yêu thích. Trang phục của các bạn trẻ gen Z thường có xu hướng thoải mái, phá cách, không bị ràng buộc và giới hạn, thể hiện rõ được sự tự do, cá tính cá nhân của giới trẻ. Đặc biệt, xu hướng&nbsp;mua sắm quần áo online&nbsp;trong thời đại công nghệ số ngày nay càng khiến phong cách của Gen Z trở nên phổ biến. Cùng Routine khám phá&nbsp;phong cách thời trang...</p>
                                        
                                        <a class="see" href="/phong-cach-thoi-trang-duoc-gen-z-nhiet-tinh-lang-xe-2023" title="Xem thêm">
                                            <span><svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32V224H48c-17.7 0-32 14.3-32 32s14.3 32 32 32H192V432c0 17.7 14.3 32 32 32s32-14.3 32-32V288H400c17.7 0 32-14.3 32-32s-14.3-32-32-32H256V80z"></path></svg></span> Xem thêm
                                        </a>
                                        
                                    </div>

                                    <div class="time-post">
                                        Ngày 26, Tháng 08, 2023
                                    </div>
                                </div>

                            </div>
						</div>

							
						<div class="col-12 col-md-6 col-lg-6 col-xl-4 col-fix">
							<div class="item-blog">
                                <div class="block-thumb">
                                    
                                    <a class="thumb" href="/5-cach-phoi-do-voi-ao-varsity-giup-ban-trong-cuc-chat" title="5 cách phối đồ với áo varsity giúp bạn trông cực chất">
                                        <img width="512" height="385" class="lazyload loaded" src="https://bizweb.dktcdn.net/100/491/897/articles/phoi-do-voi-ao-varsity.png?v=1693031786527" data-src="https://bizweb.dktcdn.net/100/491/897/articles/phoi-do-voi-ao-varsity.png?v=1693031786527" alt="5 cách phối đồ với áo varsity giúp bạn trông cực chất" data-was-processed="true">
                                    </a>
                                    
                                    <div class="info">


                                        <h3>
                                            <a class="line-clamp line-clamp-1" href="/5-cach-phoi-do-voi-ao-varsity-giup-ban-trong-cuc-chat" title="5 cách phối đồ với áo varsity giúp bạn trông cực chất">5 cách phối đồ với áo varsity giúp bạn trông cực chất</a>
                                        </h3>
                                        <p class="justify line-clamp line-clamp-3">Sự trở lại của thời trang retro đã hồi sinh những items cổ điển như quần ống loe, giày oxford, áo gile,... và không thể không kể đến là chiếc&nbsp;áo&nbsp;varsity jacket&nbsp;- một kiểu áo khoác bóng chày đã từng gây sốt một thời. Được lấy cảm hứng từ đồng phục thể thao của sinh viên nước Mỹ tại các trường đại học danh tiếng, không ngạc nhiên khi kiểu áo này trở nên được yêu thích rộng rãi
                            Từ một items mang biểu tượng của sự nổi bật, xuất chúng trong giáo dục, varsity jacket trở thành một phần không thể...</p>
                                        
                                        <a class="see" href="/5-cach-phoi-do-voi-ao-varsity-giup-ban-trong-cuc-chat" title="Xem thêm">
                                            <span><svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32V224H48c-17.7 0-32 14.3-32 32s14.3 32 32 32H192V432c0 17.7 14.3 32 32 32s32-14.3 32-32V288H400c17.7 0 32-14.3 32-32s-14.3-32-32-32H256V80z"></path></svg></span> Xem thêm
                                        </a>
                                        
                                    </div>

                                    <div class="time-post">
                                        Ngày 26, Tháng 08, 2023
                                    </div>
                                </div>

                            </div>
						</div>

							
						<div class="col-12 col-md-6 col-lg-6 col-xl-4 col-fix">
							<div class="item-blog">
                                <div class="block-thumb">
                                    
                                    <a class="thumb" href="/nang-dong-cung-5-cach-mix-do-voi-ao-khoac-the-thao-nam-hot" title="Năng động cùng 5 cách mix đồ với áo khoác thể thao nam hot">
                                        <img width="512" height="385" class="lazyload loaded" src="https://bizweb.dktcdn.net/100/491/897/articles/ao-hoodie-nam-dep.png?v=1693032095810" data-src="https://bizweb.dktcdn.net/100/491/897/articles/ao-hoodie-nam-dep.png?v=1693032095810" alt="Năng động cùng 5 cách mix đồ với áo khoác thể thao nam hot" data-was-processed="true">
                                    </a>
                                    
                                    <div class="info">


                                        <h3>
                                            <a class="line-clamp line-clamp-1" href="/nang-dong-cung-5-cach-mix-do-voi-ao-khoac-the-thao-nam-hot" title="Năng động cùng 5 cách mix đồ với áo khoác thể thao nam hot">Năng động cùng 5 cách mix đồ với áo khoác thể thao nam hot</a>
                                        </h3>
                                        <p class="justify line-clamp line-clamp-3">Bên cạnh những items thời trang phổ biến như áo t - shirt, quần jean, quần short, áo sơ mi, thì&nbsp;áo khoác thể thao nam&nbsp;là sản phẩm must-have trong tủ đồ của mọi chàng trai. Không chỉ ghi điểm bởi khả năng chống nắng và giữ ấm tốt, áo khoác thể thao còn đa dạng kiểu dáng, giúp người mặc dễ dàng kết hợp với nhiều trang phục, khẳng định phong cách thời trang của riêng mình.
                            Những năm gần đây,&nbsp;phối đồ layer với áo khoác thể thao&nbsp;trở thành cơn sốt với tất cả tín đồ thời trang. Dù là mùa...</p>
                                        
                                        <a class="see" href="/nang-dong-cung-5-cach-mix-do-voi-ao-khoac-the-thao-nam-hot" title="Xem thêm">
                                            <span><svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32V224H48c-17.7 0-32 14.3-32 32s14.3 32 32 32H192V432c0 17.7 14.3 32 32 32s32-14.3 32-32V288H400c17.7 0 32-14.3 32-32s-14.3-32-32-32H256V80z"></path></svg></span> Xem thêm
                                        </a>
                                        
                                    </div>

                                    <div class="time-post">
                                        Ngày 26, Tháng 08, 2023
                                    </div>
                                </div>

                            </div>
						</div>

						
					</div>
					<div class="text-center">
						
					</div>
					
				</div>
				
			</div>
			
		</div>

	</div>
</template>